language: csharp
solution: SS31.Linux.sln
install:
  - mono Protobuild.exe
  - nuget restore SS31.Linux.sln
  - mono Protobuild.exe
notifications:
  webhooks: https://webhooks.gitter.im/e/e16eb7ad58cd32da5f2b
